spring:
  datasource:
    url: jdbc:mysql://1.12.248.64:3306/demo01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: qaz123WSX
    driver-class-name: com.mysql.cj.jdbc.Driver