spring:
  datasource:
    url: jdbc:mysql://1.12.248.64:3306/demo01?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: qaz123WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      #官方推荐设置
      cachePrepStmts: true
      prepStmtCacheSize: 250
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
      useLocalSessionState: true
      rewriteBatchedStatements: true
      cacheResultSetMetadata: true
      cacheServerConfiguration: true
      elideSetAutoCommits: true
      maintainTimeStats: false
      #-------------JMX--------------------------------
      # 是否开启 JMX 默认 false
      register-mbeans: true
      # 是否允许通过 JMX 挂起和恢复连接池 默认为 false
      allow-pool-suspension: true
      # 从池中借出的连接是否默认自动提交事务 默认 true
      auto-commit: true
      # 当我从池中借出连接时，愿意等待多长时间。如果超时，将抛出 SQLException
      # 默认 30000 ms，最小值 250 ms。支持 JMX 动态修改
      connection-timeout: 30000
      # 一个连接在池里闲置多久时会被抛弃
      # 当 minimumIdle < maximumPoolSize 才生效
      # 默认值 600000 ms，最小值为 10000 ms，0表示禁用该功能。支持 JMX 动态修改
      idle-timeout: 60000
      # 多久检查一次连接的活性
      # 检查时会先把连接从池中拿出来（空闲的话），然后调用isValid()或执行connectionTestQuery来校验活性，如果通过校验，则放回池里。
      # 默认 0 （不启用），最小值为 30000 ms，必须小于 maxLifetime。支持 JMX 动态修改
      keepalive-time: 0
      # 当一个连接存活了足够久，HikariCP 将会在它空闲时把它抛弃
      # 默认 1800000  ms，最小值为 30000 ms，0 表示禁用该功能。支持 JMX 动态修改
      max-lifetime: 1800000
      # 用来检查连接活性的 sql，要求是一个查询语句，常用select 'x'
      # 如果驱动支持 JDBC4.0，建议不设置，这时默认会调用  Connection.isValid() 来检查，该方式会更高效一些
      # 默认为空
#      connection-test-query:

      # 池中至少要有多少空闲连接。
      # 当空闲连接 < minimumIdle，总连接 < maximumPoolSize 时，将新增连接
      # 默认等于 maximumPoolSize。支持 JMX 动态修改
      minimum-idle: 5
      # 池中最多容纳多少连接（包括空闲的和在用的）
      # 默认为 10。支持 JMX 动态修改
      maximum-pool-size: 10

      # 用于记录连接池各项指标的 MetricRegistry 实现类
      # 默认为空，只能通过代码设置
      # metricRegistry=

      # 用于报告连接池健康状态的 HealthCheckRegistry 实现类
      # 默认为空，只能通过代码设置
      # healthCheckRegistry=

      # 连接池名称。
      # 默认自动生成
      pool-name: hikari_cp
