server:
  port: 1010

spring:
  profiles:
    active: @profiles.active@

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  #开启sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  data:
    redis:
      database: 0           # 默认数据库
      host: 127.0.0.1       # 主机地址
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
      port: 6379            # 端口
      timeout: 3000         # 超时时间

